# Generated by Django 6.0.5 on 2026-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image/'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_products/'),
        ),
    ]
