# Generated by Django 6.0.5 on 2026-06-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_store_image_alter_shopproduct_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='store_name',
        ),
    ]
