# Generated by Django 6.0.5 on 2026-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_item_name_alter_listing_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
