# Generated by Django 6.0.5 on 2026-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_item_description_listing_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
