# Generated by Django 6.0.5 on 2026-06-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_status_listingitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending seller confirmation', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='listingItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='listings.listingitem'),
        ),
    ]
